### ISSUE TITLE
Function returns parser error with version 12.4.2

### ISSUE THREAD

**Issue by AudLaw** [uber/tcurl#42]
Issue with using tcurl to hit this endpoint M::N defined as below:
```
struct Params {
1: required string uuid
2: optional string id
}

service M {
bool N(
1: required Params params
)
```

Get this assertion error:
```
AssertionError: "Can't get reader/writer for definition with unknown type undefined" undefined "undefined"
at Thrift.resolve (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:237:16)
at ThriftField.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:59:27)
at ThriftStruct.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/struct.js:184:28)
at Thrift.link (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:199:32)
at new Thrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/node_modules/thriftrw/thrift.js:69:10)
at new TChannelAsThrift (/usr/lib/node_modules/tcurl/node_modules/tchannel/as/thrift.js:46:17)
at asThrift (/usr/lib/node_modules/tcurl/index.js:324:18)
at onIdentified (/usr/lib/node_modules/tcurl/index.js:278:13)
at finish (/usr/lib/node_modules/tcurl/node_modules/tchannel/peer.js:266:9)
at Array.onIdentified as 1
```

Not seeing the problem after switching back to tcurl 4.12.1 from 4.12.2

**Comment by prashantv** [comment]
@kriskowal thriftrw issue?

**Comment by AudLaw** [comment]
Should have mentioned, think may be https://github.com/uber/thriftrw/issues/58
