### ISSUE TITLE
Cannot send i64s via JSON in arg3's

### ISSUE THREAD

**Issue by rssathe** [uber/tcurl#54]
```
TCURL ERROR: Got unexpected unserializable thrift for arg3 ~ { endpoint: 'Chronotrigger::scheduleJob',
  direction: 'out.request',
  ok: undefined,
  bodyErr:
   { [TchannelThriftHandlerStringifyErrorBodyFailedError: Could not stringify body (res2) argument.
   Expected Thrift serializable res2 for endpoint Chronotrigger::scheduleJob.]
     type: 'tchannel-thrift-handler.stringify-error.body-failed',
     message: 'Could not stringify body (res2) argument.\nExpected Thrift serializable res2 for endpoint Chronotrigger::scheduleJob.',
     isSerializationError: true,
     endpoint: 'Chronotrigger::scheduleJob',
     ok: undefined,
     body: { strategy: 'NAIVE', job: [Object] },
     direction: 'out.request',
     name: 'TchannelThriftHandlerStringifyErrorBodyFailedError',
     causeMessage: 'AString::uglify expects a Buffer; received number Number',
     origMessage: 'AString::uglify expects a Buffer; received number Number',
     fullType: 'tchannel-thrift-handler.stringify-error.body-failed~!~error.wrapped-unknown' } }

/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/index.js:294
            throw e;
                  ^
Error: Got unexpected unserializable thrift for arg3
    at DebugLogStream.write (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/debug-logtron/backends/debug-log-backend.js:103:15)
    at DebugLogtron._log (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/debug-logtron/index.js:57:18)
    at DebugLogtron.error (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/debug-logtron/index.js:81:10)
    at TChannelAsThrift.stringify [as _stringify] (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/tchannel/as/thrift.js:366:21)
    at TChannelAsThrift.send (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/tchannel/as/thrift.js:187:32)
    at asThrift (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/index.js:286:16)
    at onIdentified (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/index.js:225:13)
    at finish (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/tchannel/peer.js:259:9)
    at Array.onIdentified [as 1] (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/tchannel/peer.js:250:9)
    at DefinedEvent.emit (/Users/rssathe/.nvm/v0.10.32/lib/node_modules/tcurl/node_modules/tchannel/lib/event_emitter.js:90:25)
```

**Comment by Raynos** [comment]
We need to support sending integers. We cannot express a Buffer in tcurl.

This means:

 - thriftrw needs to support serializing both a Number and a Buffer[8] into i64
 - pass it through to thrifrw

**Comment by kriskowal** [comment]
Have you tried an array of bytes?

**Comment by rssathe** [comment]
I have not no

**Comment by kriskowal** [comment]
array of bytes won't work, looking at thriftrw. we could probably make it work though. we could probably also coerce strings of hex.

**Comment by Raynos** [comment]
we should support converting Number -> int64. Whether that is in thriftrw or tcurl.

**Comment by rssathe** [comment]
agreed

**Comment by rssathe** [comment]
Do you want a pr for this? I might work on it later if I have some time if no one is working on it. Should we do this in thriftw or tcurl?

**Comment by kriskowal** [comment]
@rssathe We should do this in thriftrw. PR welcome! thriftrw/i64.js is the place to look.

**Comment by kriskowal** [comment]
This issue should be addressed by https://github.com/uber/thriftrw/pull/62, which I will roll into the next tcurl release and deploy.

**Comment by kriskowal** [comment]
Coming up in the next release.

**Comment by Willyham** [comment]
This is now fixed
